#!/usr/bin/env node
"use strict";

const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.resolve(__dirname, "..");
const TARGET = path.join(ROOT, "public", "app.js");
const SOURCES = [
  "src/client/app/client-activity.js",
  "src/client/app/core.js",
  "src/client/app/canvas-runtime.js",
  "src/client/app/visual-explainer.js",
  "src/client/app/persistence.js",
  "src/client/app/ai-runtime.js",
  "src/client/app/canvas-agent-runtime.js",
  "src/client/app/studio-navigator.js",
  "src/client/app/keyboard-shortcuts.js",
  "src/client/app/ui-bootstrap.js",
];
const BANNER = "// Generated by scripts/build-client.js from src/client/app. Do not edit this file directly.";

function compiledSource() {
  const sections = SOURCES.map(file => fs.readFileSync(path.join(ROOT, file), "utf8").trimEnd());
  return `${BANNER}\n${sections.join("\n")}\n`;
}

function main(argv = process.argv.slice(2)) {
  const source = compiledSource();
  if (argv.includes("--check")) {
    const current = fs.existsSync(TARGET) ? fs.readFileSync(TARGET, "utf8") : "";
    if (current !== source) {
      console.error("public/app.js is stale. Run `npm run build:client`.");
      return 1;
    }
    return 0;
  }
  fs.writeFileSync(TARGET, source);
  console.log(`Built ${path.relative(ROOT, TARGET)} from ${SOURCES.length} source files.`);
  return 0;
}

if (require.main === module) process.exitCode = main();

module.exports = { BANNER, SOURCES, compiledSource, main };
